"""
Report configuration for AQUILA Industrial Quarterly Report.
Update this file each quarter before generating a new report.
"""
import os

# ── Quarter Settings ─────────────────────────────────────────
REPORT_YEAR = 2025
REPORT_QUARTER = 4
REPORT_LABEL = f"Q{REPORT_QUARTER} {REPORT_YEAR}"
REPORT_TITLE = "Austin Industrial Market Report"
GENERATED_BY = "Generated by Atlas, maintained by Nelson Lin"

# ── Data Source Paths (Q: drive) ─────────────────────────────
DATA_ROOT = rf"Q:\0-Quarterly Reports\0-Industrial\{REPORT_YEAR} Q{REPORT_QUARTER}"

SUBMARKET_TABLES = os.path.join(
    DATA_ROOT, f"Tables and Graphs [Q{REPORT_QUARTER}]", "Tables",
    f"{REPORT_YEAR}Q{REPORT_QUARTER}_submarket_tables_industrial.xlsx"
)
BUILDING_LIST = os.path.join(
    DATA_ROOT, f"Building Lists [Q{REPORT_QUARTER}]",
    f"{REPORT_QUARTER}Q {REPORT_YEAR} - building_list_industrial.xlsx"
)
PIPELINE = os.path.join(
    DATA_ROOT, f"Development Pipeline [Q{REPORT_QUARTER}]",
    f"{REPORT_YEAR} Q{REPORT_QUARTER} Development Pipeline.xlsx"
)
LARGE_AVAIL = os.path.join(
    DATA_ROOT, f"Large Availabilities [Q{REPORT_QUARTER}]",
    f"{REPORT_YEAR} Q{REPORT_QUARTER} Large Availabilities.xlsx"
)
MAJOR_LEASES_SALES = os.path.join(
    DATA_ROOT, f"Major Sales and Leases [Q{REPORT_QUARTER}]",
    f"{REPORT_YEAR} Q{REPORT_QUARTER} Industrial Major Sales and Leases.xlsx"
)
QUARTERLY_CHANGES_DIR = os.path.join(
    DATA_ROOT, f"Quarterly Changes [Q{REPORT_QUARTER}]"
)

# ── Output Paths ─────────────────────────────────────────────
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORTS_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(REPORTS_DIR, "industrial", f"{REPORT_YEAR}_Q{REPORT_QUARTER}")
CHARTS_DIR = os.path.join(OUTPUT_DIR, "charts")
OUTPUT_PDF = os.path.join(
    OUTPUT_DIR,
    f"AQUILA_Industrial_Report_{REPORT_YEAR}_Q{REPORT_QUARTER}.pdf"
)

# ── Template & Static Paths ──────────────────────────────────
TEMPLATES_DIR = os.path.join(REPORTS_DIR, "templates")
STATIC_DIR = os.path.join(REPORTS_DIR, "static")
LOGO_PATH = os.path.join(REPO_ROOT, "Aquila_Logo2.png")

# ── Supabase Config ──────────────────────────────────────────
SUPABASE_TABLE = "market_tables_industrial"

# ── Submarket & Property Type Ordering ───────────────────────
# 7 submarkets for performance pages (Southwest excluded)
SUBMARKETS = [
    "East", "Hays County", "North Central", "Northeast",
    "South", "Southeast", "Williamson County",
]

# 2 property types per submarket
PROPERTY_TYPES = ["Industrial", "Flex"]

# Building list sheets: 8 submarkets × 2 types = 16 sheets
# (Southwest included in building list only)
BUILDING_LIST_SUBMARKETS = [
    "East", "Hays County", "North Central", "Northeast",
    "South", "Southeast", "Southwest", "Williamson County",
]

# ── Performance Config ───────────────────────────────────────
PERFORMANCE_QUARTERS = 8
PERFORMANCE_START_QUARTER = "2024 Q1"

# ── Chart Dimensions (pixels) ────────────────────────────────
CHART_WIDTH = 1100
CHART_HEIGHT = 340
CHART_SCALE = 3
CHART_SMALL_WIDTH = 520
CHART_SMALL_HEIGHT = 320
