"""
Report configuration for AQUILA Office Quarterly Report.
Update this file each quarter before generating a new report.
"""
import os

# ── Quarter Settings ─────────────────────────────────────────
REPORT_YEAR = 2025
REPORT_QUARTER = 4
REPORT_LABEL = f"Q{REPORT_QUARTER} {REPORT_YEAR}"
REPORT_TITLE = "Austin Office Market Report"
GENERATED_BY = "Generated by Atlas, maintained by Nelson Lin"

# ── Data Source Paths (Q: drive) ─────────────────────────────
DATA_ROOT = rf"Q:\0-Quarterly Reports\0-Office\{REPORT_YEAR} Q{REPORT_QUARTER}"

SUBMARKET_TABLES = os.path.join(
    DATA_ROOT, f"Tables and Graphs [Q{REPORT_QUARTER}]",
    f"submarket_tables_office_q{REPORT_QUARTER}.xlsx"
)
AVAILABILITY_TABLES = os.path.join(
    DATA_ROOT, f"Tables and Graphs [Q{REPORT_QUARTER}]", "Appendix",
    "Availability Tables.xlsx"
)
OFFICE_AVAIL = os.path.join(
    DATA_ROOT, f"Large Availabilities & Maps [Q{REPORT_QUARTER}]",
    "Office Avail.xlsx"
)
MAJOR_LEASES_SALES = os.path.join(
    DATA_ROOT, f"Major Leases and Sales [Q{REPORT_QUARTER}]",
    f"Major Leases and Sales {REPORT_YEAR} {REPORT_QUARTER}Q.xlsx"
)
CITYWIDE_PIPELINE = os.path.join(
    DATA_ROOT, f"Citywide Pipeline [Q{REPORT_QUARTER}]",
    f"Citywide Pipeline {REPORT_YEAR} Q{REPORT_QUARTER}.xlsx"
)
BUILDING_LIST = os.path.join(
    DATA_ROOT, f"Building Lists [Q{REPORT_QUARTER}]",
    f"{REPORT_QUARTER}Q {REPORT_YEAR} Building List.xlsx"
)
QUARTERLY_CHANGES_DIR = os.path.join(
    DATA_ROOT, f"Quarterly Changes [Q{REPORT_QUARTER}]"
)

# ── Output Paths ─────────────────────────────────────────────
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORTS_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(REPORTS_DIR, "office", f"{REPORT_YEAR}_Q{REPORT_QUARTER}")
CHARTS_DIR = os.path.join(OUTPUT_DIR, "charts")
OUTPUT_PDF = os.path.join(
    OUTPUT_DIR,
    f"AQUILA_Office_Report_{REPORT_YEAR}_Q{REPORT_QUARTER}.pdf"
)

# ── Template & Static Paths ──────────────────────────────────
TEMPLATES_DIR = os.path.join(REPORTS_DIR, "templates")
STATIC_DIR = os.path.join(REPORTS_DIR, "static")
LOGO_PATH = os.path.join(REPO_ROOT, "data", "Aquila_Logo2.png")

# ── Submarket / Section Ordering ─────────────────────────────
# Competitive set pages (table_type = "competitive set")
SUBMARKETS_COMP = ["Citywide", "CBD", "Northwest", "Southwest", "East"]

# Micromarket pages (table_type = "micromarket")
MICROMARKETS = [
    "Domain", "Shepherd Mountain", "Near Northwest",
    "Far Northwest", "Near Southwest", "Far Southwest",
]

# Overall performance pages (table_type = "overall")
SUBMARKETS_OVERALL = ["CBD", "Northwest", "Southwest", "East"]

# Submarkets that get KPI header + availability + development pages
SUBMARKETS_WITH_DETAIL = ["CBD", "Northwest", "Southwest", "East"]

# Building list sheet names → display names (for building list pages)
BUILDING_LIST_SHEETS = {
    "CBD": "CBD",
    "East": "East",
    "Domain": "Domain",
    "Shepherd Mountain": "Shepherd Mountain/2222",
    "Near Northwest": "Near Northwest",
    "Far Northwest": "Far Northwest",
    "Near Southwest": "Near Southwest",
    "Far Southwest": "Far Southwest",
}

# Micromarket → building list sheet mapping
MICRO_TO_BUILDING_SHEET = {
    "Domain": "Domain",
    "Shepherd Mountain": "Shepherd Mountain",
    "Near Northwest": "Near Northwest",
    "Far Northwest": "Far Northwest",
    "Near Southwest": "Near Southwest",
    "Far Southwest": "Far Southwest",
}

# ── Supabase Query Config ────────────────────────────────────
# Last N quarters to show on performance pages
PERFORMANCE_QUARTERS = 8
# The earliest quarter to include on performance pages
PERFORMANCE_START_QUARTER = "2024 Q1"

# ── Chart Dimensions (pixels) ────────────────────────────────
CHART_WIDTH = 1100
CHART_HEIGHT = 340
CHART_SCALE = 3  # For high-DPI export
CHART_SMALL_WIDTH = 520
CHART_SMALL_HEIGHT = 320
